name: 🤖 Automated Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # Every Saturday at midnight UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8cb0d4a6ab7d8bb90460a005f7bd33b80dd07ca8 # v44.2.5
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.REPOSITORY_TOKEN }}
