name: 🤖 Automated Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # Every Saturday at midnight UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@83ec54fee49ab67d9cd201084c1ff325b4b462e4 # v46.1.10
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.REPOSITORY_TOKEN }}
